// Copyright (c) 2026 Softside Tech Pty Ltd. All rights reserved.
// SPDX-License-Identifier: MPL-2.0

//! Raw FFI bindings to FFmpeg libavcodec, libavutil, and libswscale.
//!
//! Generated by bindgen from the vendored FFmpeg headers. Use the safe
//! wrappers in `video-engine` instead of calling these directly.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
